version: '3.8'

services:
  conferencia-service:
    build: ./ConferenceMicroservice
    container_name: conferencia-service
    ports:
      - "8081:8081" # Ajusta el puerto según lo necesites
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - rabbitmq

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
    depends_on:
      - keycloak

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # Asume que el frontend corre en puerto 3000
    networks:
      - app-network
    depends_on:
      - conferencia-service
      - review-service

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/keycloak-realm-config.json # Importar configuración
    volumes:
      - ./keycloak/keycloak-realm-config.json:/opt/keycloak/data/import/keycloak-realm-config.json
    ports:
      - "8080:8080"
    networks:
      - app-network
    rabbitmq:
      build:
        context: ./rabbitmq
      container_name: rabbitmq
      networks:
        - app-network
      ports:
        - "5672:5672"
        - "15672:15672"

networks:
  app-network:
    driver: bridge
