server:
  port: 8083 # Puerto del Gateway

spring:
  application:
    name: api-gateway
  main:
      web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: ConferenceMicroservice
          uri: lb://CONFERENCEMICROSERVICE # URL del microservicio de conferencias
          predicates:
              - Path=/api/** # Rutas que redirige al microservicio
        # Rutas que redirige al microservicio
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ConferenceMaster
          jwk-set-uri: http://keycloak:8080/realms/ConferenceMaster/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: ${HOSTNAME}
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG