server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: microservicioConferencias
          uri: http://localhost:8081 # Dirección del servicio backend
          predicates:
            - Path=/api/microservicio1/**
        - id: microservicio2
          uri: http://localhost:8082
          predicates:
            - Path=/api/microservicio2/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
